name: basex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  google_fonts: ^2.3.2
  cached_network_image: ^3.2.0
  badges: ^2.0.2
  dots_indicator: ^2.1.0
  font_awesome_flutter: ^10.1.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - lib/assets/honey_tub.png
    - lib/assets/butterscotch_tub.png
    - lib/assets/chocolate_cone.png
    - lib/assets/japanese_cone.png
    - lib/assets/japanese_cup.png
    - lib/assets/mango.png
    - lib/assets/rainbow_cone.png
    - lib/assets/rainbow_cup.png
    - lib/assets/veggies.png
    - lib/assets/dairy.png
    - lib/assets/coffee.png
    - lib/assets/drinks.png
    - lib/assets/munchies.png
    - lib/assets/rice.png
    - lib/assets/biscuits.png

